/**
 * Build a .docx buffer from markdown (headings, bullets, bold).
 */
import { Document, Packer, Paragraph, TextRun, HeadingLevel } from 'docx';
import { classifyMarkdownLine } from './markdownDocx';

function runsFromInlineMarkdown(text: string): TextRun[] {
  const parts = text.split(/(\*\*.*?\*\*)/g);
  return parts.map((part) => {
    if (part.startsWith('**') && part.endsWith('**')) {
      return new TextRun({ text: part.slice(2, -2), bold: true, size: 22, font: 'Calibri' });
    }
    return new TextRun({ text: part, size: 22, font: 'Calibri' });
  });
}

export async function textToDocx(textContent: string, title: string): Promise<Buffer> {
  const children: Paragraph[] = [];

  for (const rawLine of textContent.split(/\r?\n/)) {
    const { kind, text } = classifyMarkdownLine(rawLine);

    if (kind === 'h3') {
      children.push(
        new Paragraph({
          children: [new TextRun({ text, bold: true, size: 24 })],
          heading: HeadingLevel.HEADING_3,
          spacing: { before: 200, after: 100 },
        })
      );
    } else if (kind === 'h2') {
      children.push(
        new Paragraph({
          children: [new TextRun({ text, bold: true, size: 28 })],
          heading: HeadingLevel.HEADING_2,
          spacing: { before: 240, after: 120 },
        })
      );
    } else if (kind === 'h1') {
      children.push(
        new Paragraph({
          children: [new TextRun({ text, bold: true, size: 32 })],
          heading: HeadingLevel.HEADING_1,
          spacing: { before: 360, after: 120 },
        })
      );
    } else if (kind === 'blank') {
      children.push(new Paragraph({ children: [] }));
    } else if (kind === 'bullet') {
      children.push(
        new Paragraph({
          children: runsFromInlineMarkdown(text),
          bullet: { level: 0 },
          spacing: { after: 80 },
        })
      );
    } else {
      children.push(
        new Paragraph({
          children: runsFromInlineMarkdown(text),
          spacing: { after: 80 },
        })
      );
    }
  }

  const doc = new Document({
    sections: [
      {
        properties: {},
        children: [
          new Paragraph({
            children: [new TextRun({ text: title, bold: true, size: 28, font: 'Calibri' })],
            heading: HeadingLevel.TITLE,
            spacing: { after: 240 },
          }),
          new Paragraph({
            children: [
              new TextRun({
                text: `Generated by HALO on ${new Date().toLocaleDateString()}`,
                italics: true,
                size: 18,
                font: 'Calibri',
                color: '888888',
              }),
            ],
            spacing: { after: 360 },
          }),
          ...children,
        ],
      },
    ],
  });

  return Buffer.from(await Packer.toBuffer(doc));
}
