/**
 * Build a .docx buffer from plain text (markdown-style headings and bold).
 */
import { Document, Packer, Paragraph, TextRun, HeadingLevel } from 'docx';

export async function textToDocx(textContent: string, title: string): Promise<Buffer> {
  const lines = textContent.split('\n');
  const children: Paragraph[] = [];

  for (const line of lines) {
    const trimmed = line.trim();

    if (trimmed.startsWith('## ')) {
      children.push(
        new Paragraph({
          children: [new TextRun({ text: trimmed.replace('## ', ''), bold: true, size: 28 })],
          heading: HeadingLevel.HEADING_2,
          spacing: { before: 240, after: 120 },
        })
      );
    } else if (trimmed.startsWith('# ')) {
      children.push(
        new Paragraph({
          children: [new TextRun({ text: trimmed.replace('# ', ''), bold: true, size: 32 })],
          heading: HeadingLevel.HEADING_1,
          spacing: { before: 360, after: 120 },
        })
      );
    } else if (trimmed === '') {
      children.push(new Paragraph({ children: [] }));
    } else {
      const parts = trimmed.split(/(\*\*.*?\*\*)/g);
      const runs: TextRun[] = parts.map(part => {
        if (part.startsWith('**') && part.endsWith('**')) {
          return new TextRun({ text: part.slice(2, -2), bold: true, size: 22, font: 'Calibri' });
        }
        return new TextRun({ text: part, size: 22, font: 'Calibri' });
      });
      children.push(new Paragraph({ children: runs, spacing: { after: 80 } }));
    }
  }

  const doc = new Document({
    sections: [{
      properties: {},
      children: [
        new Paragraph({
          children: [new TextRun({ text: title, bold: true, size: 28, font: 'Calibri' })],
          heading: HeadingLevel.TITLE,
          spacing: { after: 240 },
        }),
        new Paragraph({
          children: [new TextRun({
            text: `Generated by HALO on ${new Date().toLocaleDateString()}`,
            italics: true, size: 18, font: 'Calibri', color: '888888',
          })],
          spacing: { after: 360 },
        }),
        ...children,
      ],
    }],
  });

  return Buffer.from(await Packer.toBuffer(doc));
}
